### ISSUE TITLE
File 

### ISSUE THREAD

**Issue by rgoalcast** [eleanorlutz/mars_geology_atlas_of_space#1]
readname = "A:/ATLAS_OF_SPACE/DEMs/Mars_Viking.jpg"

Which image is mentioned in above command line in file 2_landing_sites.ipynb ?

**Comment by eleanorlutz** [comment]
Sorry for the delayed response on this! The file is [this one](https://github.com/Stellarium/stellarium/blob/master/textures/mars.png) from the open source project [Stellarium](https://github.com/Stellarium/stellarium/tree/master/textures). The one on their website now is updated and looks nicer, but I'm including the original image below in case you needed that one specifically. 

![Mars_Viking](https://user-images.githubusercontent.com/6994487/99887127-a6d46100-2c0f-11eb-983f-56fe59ef89f1.jpg)
